download_data:
	Python ../tools/FPBPulseExtraction.py 00719502000 943

run_model:
	Python ../radar_FM1D_refMethod.py models/943/model.txt

compare:
	Python ../tools/compare.py models/943/model data/FPB_719502000_40.434_24.4157
